from tkinter import *
window=Tk()
window.title('Document')
window.geometry('400x400')

def label():
    var_label=Label(window,text=vertical_slider.get())
    var_label.grid(row=0,column=6)
    var_label=Label(window,text=vertical_slider1.get())
    var_label.grid(row=0,column=7)
    var_label=Label(window,text=vertical_slider2.get())
    var_label.grid(row=0,column=8)
    var_label=Label(window,text=vertical_slider3.get())
    var_label.grid(row=0,column=9)
    var_label=Label(window,text=vertical_slider4.get())
    var_label.grid(row=0,column=10)
    var_label=Label(window,text=vertical_slider5.get())
    var_label.grid(row=0,column=11)

vertical_slider=Scale(window, from_=0, to =400,orient=VERTICAL)
vertical_slider.grid(row=0,column=0)
vertical_slider1=Scale(window, from_=0, to =400,orient=VERTICAL)
vertical_slider1.grid(row=0,column=1)
vertical_slider2=Scale(window, from_=0, to =400,orient=VERTICAL)
vertical_slider2.grid(row=0,column=2)
vertical_slider3=Scale(window, from_=0, to =400,orient=VERTICAL)
vertical_slider3.grid(row=0,column=3)
vertical_slider4=Scale(window, from_=0, to =300,orient=VERTICAL)
vertical_slider4.grid(row=0,column=4)
vertical_slider5=Scale(window, from_=0, to =400,orient=VERTICAL)
vertical_slider5.grid(row=0,column=5)

var_button=Button(window,text='click here for values',command=label)
var_button.grid(row=0,column=12)
window.mainloop()
